---
- hosts: all
  become: yes
  tasks:
    - name: Rotate logs (before compression)
      shell: "logrotate -f /etc/logrotate.conf"

    - name: Compress logs (before upload)
      shell: "find /var/log -name '*.log.1' | xargs gzip"

    - name: Upload logs
      synchronize:
        src: "/var/log"
        dest: "{{ zuul.executor.log_root }}"
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - '--exclude=journal/'

    - name: Upload configuration
      synchronize:
        src: "/etc"
        dest: "{{ zuul.executor.log_root }}"
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts: []
      # broken symlink cause rsync return code 23
      ignore_errors: yes

    - name: Get some commands output
      script: collect_commands.sh

    - name: Upload commands
      synchronize:
        src: "/tmp/commands"
        dest: "{{ zuul.executor.log_root }}"
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts: []
