---
- hosts: all
  vars:
    do_not_install_packages_after_build: true
  roles:
    - debian-packaging
  tasks:
    - name: Run the installation script
      become: yes
      command: >
          ansible-playbook -i inventories/uc-engine uc-engine.yml
          --extra-vars wazo_distribution={{ wazo_distribution | default('wazo-dev-bookworm') }}
          --extra-vars wazo_distribution_upgrade={{ wazo_distribution_upgrade | default('wazo-dev-bookworm') }}
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-ansible"

    - name: create acceptance config
      blockinfile:
        create: yes
        path: ~/.wazo-acceptance/config.yml
        block: |
          debug:
            global: True

            acceptance: True
            linphone: True
            xivo_test_helpers: True
          instances:
            default:
              wazo_host: "{{ ansible_docker0.ipv4.address }}"

    - import_role: name=wazo-tox
      vars:
        tox_envlist: setup
        zuul_work_dir: "{{ zuul.project.src_dir }}/../wazo-acceptance"

    - import_role: name=wazo-tox
      vars:
        tox_envlist: behave
        tox_extra_args: "-- --no-capture --no-color features/daily"
        zuul_work_dir: "{{ zuul.project.src_dir }}/../wazo-acceptance"
