---
- hosts: all
  tasks:
    - name: Check if integration logs exist
      stat:
        path: /tmp/docker-logs
      register: docker_logs

    - name: Compress integration logs
      shell: |
        gzip {{ docker_logs.stat.path }}/*
      when: docker_logs.stat.exists

    - name: Fetch integration logs
      synchronize:
        src: '{{ docker_logs.stat.path }}/'
        dest: '{{ zuul.executor.log_root }}/docker/'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts: []
      when: docker_logs.stat.exists
